workflows:
  build-vnno:
    name: VNNO Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - unzip vnno_flutter_app.zip -d
      - flutter pub get
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
